export const GET_CURRENT_PLAYING_LIST = "GET_CURRENT_PLAYING_LIST" //获取当前正在播放列表数据
export const ADD_TO_CURRENT_PLAYINGLIST = 'ADD_TO_CURRENT_PLAYINGLIST' //添加到当前正在播放列表
export const PLAYING_RADIO_INFO = 'PLAYING_RADIO_INFO'
export const REGENERRATION_ORDER_PLAY_LIST = "REGENERRATION_ORDER_PLAY_LIST"
export const ORIGN_PLAYING_INDEX = "ORIGN_PLAYING_INDEX"
export const ORDER_PLAYING_INDEX = "ORDER_PLAYING_INDEX"
export const UPDATE_CURRENT_PLAYING_SONG = "UPDATE_CURRENT_PLAYING_SONG"
export const UPDATE_ROOT_CURRENT_PLAYING_SONG = "UPDATE_ROOT_CURRENT_PLAYING_SONG"
export const DEL_CURRENT_LIST_SONG = "DEL_CURRENT_LIST_SONG" //删除正在播放列表的歌曲
export const UPDATE_PLAY_ERROR_COUNT = 'UPDATE_PLAY_ERROR_COUNT' //连续播放错误的歌曲数量
export const PLAY_STATE_RESETED = 'PLAY_STATE_RESETED'

export const GET_LOCAL_SONG_LIST = "GET_LOCAL_SONG_LIST"
export const ADD_TO_LOCAL_SONG_LIST = "ADD_TO_LOCAL_SONG_LIST" //添加到本地列表
export const DELETE_FROM_LOCAL_SONG_LIST = "DELETE_FROM_LOCAL_SONG_LIST"
export const UPDATE_LOCAL_LIST_PLAYING_INDEX = "UPDATE_LOCAL_LIST_PLAYING_INDEX" //本地列表中正在播放的歌曲的索引
export const SORT_LOCAL_SONG_LIST = "SORT_LOCAL_SONG_LIST"
export const UPDATE_LOCAL_SONG_DURATION = "UPDATE_LOCAL_SONG_DURATION"
export const UPDATE_LOCAL_CURRENTPAGE_DATA = "UPDATE_LOCAL_CURRENTPAGE_DATA" //更新本地列表当前页数据

export const GET_HISTORY_SONG_LIST = "GET_HISTORY_SONG_LIST"
export const DELETE_FROM_HISTORY_SONG_LIST = "DELETE_FROM_HISTORY_SONG_LIST"
export const UPDATE_HISTORY_LIST_PLAYING_INDEX = "UPDATE_HISTORY_LIST_PLAYING_INDEX" //播放历史中正在播放的歌曲的索引
export const UPDATE_HISTORY_SONG_DURATION = "UPDATE_HISTORY_SONG_DURATION"
export const UPDATE_HISTORY_CURRENTPAGE_DATA = "UPDATE_HISTORY_CURRENTPAGE_DATA" //更新播放历史当前页数据

export const PLAY_MODE = 'PLAY_MODE'
export const VOLUME = 'VOLUME'
export const AUTO_PLAY = "AUTO_PLAY"
export const IS_MUTED = "IS_MUTED"
export const DISPLAY_INFO = "DISPLAY_INFO"
export const LAST_PLAY_MODE = "LAST_PLAY_MODE"
export const CLOSE_MODE = "CLOSE_MODE"
export const GET_SHORTCUTS = "GET_SHORTCUTS"
export const MODIFY_SHORTCUT_ITEM = "MODIFY_SHORTCUT_ITEM"
export const DOWNLOAD_FOLDER = "DOWNLOAD_FOLDER"
export const CACHE_FOLDER = "CACHE_FOLDER"
export const CACHE_SIZE = "CACHE_SIZE"
export const DOWNLOAD_LYRIC_WITH_SONG = "DOWNLOAD_LYRIC_WITH_SONG"
export const DEFAULI_PLAYER = "DEFAULI_PLAYER"
export const ENABLE_SHORTCUT = "ENABLE_SHORTCUT"

export const CURRENT_PLATING_TIME_POS = 'CURRENT_PLATING_TIME_POS'
export const CURRENT_PLATING_SONG_LYRIC = 'CURRENT_PLATING_SONG_LYRIC'

export const LIST_SELECTED_LINES = 'LIST_SELECTED_LINES' //存放除了正在播放列表外其他所有列表的选中状态，由于各个列表不会同时展示，所以不会有问题
export const LIST_SELECTED_SONGIDS = 'LIST_SELECTED_SONGIDS'

//search
export const KEYWORD = "KEYWORD"
export const SEARCH_NUM = "SEARCH_NUM"
export const SEARCH_LIST = "SEARCH_LIST"
export const SEARCH_LOADDING = "SEARCH_LOADDING"
export const SEARCH_HISTORY = 'SEARCH_HISTORY'
export const SUG_ONLINE_LIST = "SUG_ONLINE_LIST"
export const SUG_LOCAL_SONG_LIST = 'SUG_LOCAL_SONG_LIST'

//gedan
export const GEDAN_LIST = "GEDAN_LIST"
export const CHANNEL_LIST = 'CHANNEL_LIST'
export const GEDAN_INFO = 'GEDAN_INFO'
export const GEDAN_SONG_LIST = 'GEDAN_SONG_LIST'
export const GEDAN_BASE_INFO = 'GEDAN_BASE_INFO'
export const USER_DIY_LIST = 'USER_DIY_LIST'

//radio
export const RADIO_CATEGORY = "RADIO_CATEGORY"
export const RADIO_ALL_SCENE = 'RADIO_ALL_SCENE'
export const SCENE_SONG = 'SCENE_SONG'
export const PRIVATE_RADIO = 'PRIVATE_RADIO'
export const CURRENT_PLAYING_PRIVATE_RADIO = 'CURRENT_PLAYING_PRIVATE_RADIO'

// context menu

export const CONTEXTMENU_TYPE = 'CONTEXTMENU_TYPE'

//local focus images
export const GET_LOCAL_FOCUS_IMAGES = 'GET_LOCAL_FOCUS_IMAGES'
export const STOR_LOCAL_FOCUS_IMAGES = 'STOR_LOCAL_FOCUS_IMAGES'
export const DELETE_LOCAL_FOCUS_IMAGES = 'DELETE_LOCAL_FOCUS_IMAGES'

//推荐页
export const INDEX_RECOMMEND_ALBUM_LIST = "INDEX_RECOMMEND_ALBUM_LIST"
export const INDEX_RECOMMEND_NEW_BANGDAN_LIST = 'INDEX_RECOMMEND_NEW_BANGDAN_LIST'
export const INDEX_RECOMMEND_HOT_BANGDAN_LIST = 'INDEX_RECOMMEND_HOT_BANGDAN_LIST'
export const INDEX_RECOMMEND_GEDAN_LIST = 'INDEX_RECOMMEND_GEDAN_LIST'
export const INDEX_RECOMMEND_MV_LIST = 'INDEX_RECOMMEND_MV_LIST'
export const INDEX_RECOMMEND_DAILY_LIST = 'INDEX_RECOMMEND_DAILY_LIST'
export const INDEX_RECOMMEND_DAILY_LIST_2 = 'INDEX_RECOMMEND_DAILY_LIST_2'
export const INDEX_RECOMMEND_DAILY_LIST_3 = 'INDEX_RECOMMEND_DAILY_LIST_3'
export const INDEX_RECOMMEND_JXGEDAN_LIST = 'INDEX_RECOMMEND_JXGEDAN_LIST'

//bangdan
export const ALL_BANGDAN_LIST = 'ALL_BANGDAN_LIST'
export const BANGDAN_SONG_LIST = 'BANGDAN_SONG_LIST'

//singer
export const ALL_SINGER_LIST = 'ALL_SINGER_LIST'
export const SINGER_INFO = 'SINGER_INFO'
export const SINGER_SONG_LIST = 'SINGER_SONG_LIST'
export const SINGER_ALBUM_LIST = 'SINGER_ALBUM_LIST'
export const HOT_SINGER_SONG_LIST = 'HOT_SINGER_SONG_LIST'

//album
export const ALBUM_INFO = "ALBUM_INFO"


//login user
export const LOGIN_USER_INFO = "LOGIN_USER_INFO"
export const LOGIN_STATUS = "LOGIN_STATUS"
export const ISSHOW_LOGIN_USER_POP = "ISSHOW_LOGIN_USER_POP"

//收藏
export const USER_FAVORITE_DIY_LIST = "USER_FAVORITE_DIY_LIST"
export const USER_FAVORITE_ALBUM_LIST = "USER_FAVORITE_ALBUM_LIST"
export const USER_FAVORITE_SINGER_LIST = "USER_FAVORITE_SINGER_LIST"
export const USER_FAVORITE_SONG_LIST = "USER_FAVORITE_SONG_LIST"

export const GET_FAVOUR_SONG_INTERVAL = 'GET_FAVOUR_SONG_INTERVAL'
export const ALL_FAVOUR_SONG_LIST = 'ALL_FAVOUR_SONG_LIST'
export const EMPTY_FAVOR_SONG_LIST = "EMPTY_FAVOR_SONG_LIST" //退出登录的时候清空收藏歌曲列表
    // export const THE_SONG_IS_FAVOUR = "THE_SONG_IS_FAVOUR"


//正在下载
export const GET_DOWNLOADING_LIST = "GET_DOWNLOADING_LIST"
export const ADD_DWONLOADING_ITEM = "ADD_DWONLOADING_ITEM"
export const NOTIFY_DOWNLOADING_END = "NOTIFY_DOWNLOADING_END"
export const UPDATE_DOWNLOADING_PROGRESS = "UPDATE_DOWNLOADING_PROGRESS"
export const DEL_DOWNLOADING_ITEMS = "DEL_DOWNLOADING_ITEMS"
export const UPDATE_DOWNLOADING_ITEM = "UPDATE_DOWNLOADING_ITEM"
export const UPDATE_DWONLOAD_TASK_ITEM = "UPDATE_DWONLOAD_TASK_ITEM"
export const STOP_ALL_DOWNLOADINGS = "STOP_ALL_DOWNLOADINGS"

//已下载
export const GET_DOWNLOADED_LIST = "GET_DOWNLOADED_LIST"
export const ADD_DWONLOADED_ITEM = "ADD_DWONLOADED_ITEM"
export const DEL_DOWNLOADED_ITEMS = "DEL_DOWNLOADED_ITEMS"
export const UPDATE_DOWNLOADED_LIST_PLAYING_INDEX = "UPDATE_DOWNLOADED_LIST_PLAYING_INDEX"
export const UPDATE_CURRENTPAGE_DOWNLOADED_DATA = "UPDATE_CURRENTPAGE_DOWNLOADED_DATA"

//自建歌单
export const ADD_NEW_DIY_LIST = "ADD_NEW_DIY_LIST"
export const DEL_DIY_LIST = "DEL_DIY_LIST"
export const ADD_SONGS_TO_DIY_LIST = "ADD_SONGS_TO_DIY_LIST"
export const DEL_SONGS_FROM_DIY_LIST = "DEL_SONGS_FROM_DIY_LIST"

export const UPDATE_SONGLIST_INFO = "UPDATE_SONGLIST_INFO"
export const GEDAN_ALL_SONG_LIST = "GEDAN_ALL_SONG_LIST"
export const MODIFY_DIY_TITLE = 'MODIFY_DIY_TITLE'

export const EMPTY_SONG_LIST = "EMPTY_SONG_LIST"

//批量操作
export const UPDATESELECTMASSITEM = "ADD_ITEM_TO_MASSOPERATION_LIST"
export const EMPTY_MASSOPERATION_LIST = "EMPTY_MASSOPERATION_LIST"
export const ADD_ITEMS_AND_CLEAR_OLD = "ADD_ITEMS_AND_CLEAR_OLD"

//MV推荐页
export const MV_RECOMMEND_LIST = "MV_RECOMMEND_LIST"
export const MV_BIGMAN_LIST = "MV_BIGMAN_LIST"
export const MV_REPLAY_LIST = "MV_REPLAY_LIST"
export const MV_SEARCH_LIST = "MV_SEARCH_LIST"

//连续包月信息
export const PAY_AUTO_INFO = "PAY_AUTO_INFO"

//设置当前播放状态
export const SET_PLAYING_STATE = "SET_PLAYING_STATE"

//新歌上架
export const NEW_RECOMMEND_ALBUM_LABLES = "NEW_RECOMMEND_ALBUM_LABLES"
export const NEW_RECOMMEND_ALBUM_DATA = "NEW_RECOMMEND_ALBUM_DATA"
export const CLEAR_NEW_RECOMMEND_ALBUM_DATA = "CLEAR_NEW_RECOMMEND_ALBUM_DATA"